### ISSUE TITLE
Nuxt Server Error Page shows up on deployment to firebase

### ISSUE THREAD

**Issue by BruceHem** [davidroyer/nuxt-ssr-firebase#1]
I'm try to setup a nuxt project with cloud functions, but it's not working. I'm following your project here as a guide. But I still got Nuxt Server Error Page.

**Comment by davidroyer** [comment]
I’ll try to do in the next few days. If the meantime, if you have repo with the source you could share or provide more details such as which version of nuxt you’re using, etc, feel free to share

**Comment by davidroyer** [comment]
@BruceHem I tried deploying last night and I received the same issue. I attempted to resolve the issue but was unable. Something has changed since I had last deployed but not sure what. Planning to spend more time this weekend and I'll update you when resolved. Thanks for making me aware of the issues.

**Comment by viktorvillalobos** [comment]
The same for me ," 504 Gateway Time-out"  in deploy.

**Comment by BruceHem** [comment]
@viktorvillalobos I get 504 when i set it nuxt config dev to true.

**Comment by viktorvillalobos** [comment]
@BruceHem now it is returning error 500, reviewing the log I realize this error

> "Billing account not configured. External network is not accessible and quotas are severely limited. Configure billing account to remove these restrictions"

[Stackoverflow answer:](https://stackoverflow.com/questions/42784135/cloud-functions-for-firebase-billing-account-not-configured)

> "The restriction is about outbound access - e.g. can your Function request resources from the general internet. Its absolutely fine to use a function to respond to a webhook, or to access Google-internal services such a the Realtime Database.
> 
> If you wanted to call a third party web service (for example) you'd need to enable billing."

So we need to pay. 🗡

**Comment by jelmerf** [comment]
Deploy seems fine here. It's just that visiting the site subsequently results in a 504 gateway timeout.

@viktorvillalobos what external network calls are taking place making that message the explanation of our 504 error? Isn't it just a warning?

It would be great if we could get this to work; nuxt and firebase together would be a potent combination IMO.

**Comment by BruceHem** [comment]
@viktorvillalobos I'm on paid plan, can't either. Get Nuxt server error page.

**Comment by BruceHem** [comment]
https://github.com/nuxt/nuxt.js/issues/2047#issuecomment-347015230
